### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by messfromspace** [conradz/esnext-loader#3]
I use js-csp library. So generators support is critical for me. Esnext-loader doesn't include regenerator runtime in build file and that's why I need to use alternative solution like `regenerator!esnext?generator=false`. It is totally fine but it would be nice if all-in-one solution will be work as it should.

Fun fact: 6to5-loader has the same problem, seems like nobody uses generators =)

Sorry for my poor English.

**Comment by messfromspace** [comment]
Ok, I've found the includeRuntime option. So now everything is awesome.

**Comment by conradz** [comment]
Good find! I hadn't used generators before, so I didn't know about this either.
